### ISSUE TITLE
jupyterlab

### ISSUE THREAD

**Issue by pfajer** [arose/nglview#677] opened 2017-08-14 19:32 UTC
- Question about usage? https://github.com/arose/nglview/issues/589
I cannot display a structure in the jupyterlab.  (installed via Alex's  devtools/nglview-jupyterlab.sh  ).

```python
import nglview as nv
import pytraj
view = nv.demo()
view
```
returns:  "A Jupyter Widget"
But no actual display.

thanks
peter

- Version report

```bash

1.0.a3+1.g3eaf051.dirty

7.0.0b0
```

- Please always double-check install guide here: https://github.com/arose/nglview#released-version
(updated frequently)

**Comment by hainm** [comment] 2017-08-14 20:07
hi, `jupyterlab` is involved quickly right now, so we won't promise anything (as stated here
https://github.com/arose/nglview#jupyterlab-user).

That's why we built a docker image for user
https://github.com/arose/nglview#docker-user

We also have a process of docker build with specific version numbers here in case you still want
to install by yourself.

- https://github.com/arose/nglview/blob/master/Dockerfile-jupyterlab
- https://github.com/arose/nglview/blob/master/Dockerfile

Hope this help.

**Comment by hainm** [comment] 2017-08-14 20:11
related issue on jupyterlab I opened a while ago: https://github.com/jupyterlab/jupyterlab/issues/2791

**Comment by hainm** [comment] 2017-08-14 21:24
Never mind about above, we specify about versions.

have you run jupyterlab in newly created env (from the script)

```
source activate jupyterlab_025
jupyterlab
```

**Comment by pfajer** [comment] 2017-08-14 23:03
Yes except that it was :

jupyterlab_0252

And I called it :

jupyter lab




On Aug 14, 2017, at 5:24 PM, Hai Nguyen <notifications@github.com<mailto:notifications@github.com>> wrote:


source activate jupyterlab_025
jupyterlab

**Comment by hainm** [comment] 2017-08-14 23:13
Thanks. I will check tonight.

**Comment by pfajer** [comment] 2017-08-14 23:23
Many thanks.   I work till about 1am, 10pm your time.

p.

On Aug 14, 2017, at 7:13 PM, Hai Nguyen <notifications@github.com<mailto:notifications@github.com>> wrote:

Thanks. I will check tonight.

**Comment by hainm** [comment] 2017-08-15 02:08
I can reproduce your error. The weird thing is that the docker version does not work too.
This is super-weird because I've been checking many times before pushing it.

So I guess we should be less excited about Jupyterlab for now and just use the regular notebook.
cheers.

**Comment by pfajer** [comment] 2017-08-15 03:09
Oooh, that’s too bad, but as you say so much for alpha releases ….   At least I know I am not a single wrong version module away from having it working.    If you stumble again on a jupyterlab release  that works like the one you had operational please let me know.

Many thanks for your prompt action

best
Peter
_______________________________
Piotr Fajer
Professor and Director Institute Molecular Biophysics
Department of Biology
Florida State University
pfajer@fsu.edu<mailto:pfajer@fsu.edu>

On Aug 14, 2017, at 10:08 PM, Hai Nguyen <notifications@github.com<mailto:notifications@github.com>> wrote:


I can reproduce your error. The weird thing is that the docker version does not work too.
This is super-weird because I've been checking many times before pushing it.

So I guess we should be less excited about Jupyterlab for now and just use the regular notebook.
cheers.

**Comment by hainm** [comment] 2017-08-15 03:40
>  If you stumble again on a jupyterlab release  that works like the one you had operational please let me know.

sure.

**Comment by hainm** [comment] 2017-08-15 04:36
@pfajer  I think I make `nglview` works with `jupyterlab` again: https://github.com/arose/nglview/commit/e6adc2966ab64c763244266119f37a7e6f19cf40

Please follow below
```bash
cd /nglview/root/folder
git clean -fdx .
git pull
source devtools/nglview-jupyterlab.sh

# then go to another folder (to avoid import nglview source code)
jupyter lab
```

I've tried above several times and seems work for me.

![jupyterlab](https://user-images.githubusercontent.com/4451957/29302363-74837f90-8151-11e7-8285-90ebb354ca74.png)

![jupyterlab-version](https://user-images.githubusercontent.com/4451957/29302402-c5c0555e-8151-11e7-8e41-ea90f3fa9951.png)

**Comment by pfajer** [comment] 2017-08-15 04:38
WOW !!!!!!!!
You made my day

I will try first thing tomorrow morning (I am afraid I will screw up something at this time)

Peter

On Aug 15, 2017, at 12:36 AM, Hai Nguyen <notifications@github.com<mailto:notifications@github.com>> wrote:


@pfajer<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_pfajer&d=DwMFaQ&c=HPMtquzZjKY31rtkyGRFnQ&r=8waEScVAJus7pLy7oGBweQ&m=X5merpplkg4e7UWlUQRNAQ276g5qnj7jVo3_jS2aVYI&s=x2uWY8Utq4VmNcx2LdZPmz9YuA92QrBuPgkykTJfrKY&e=> I think I make nglview works with jupyterlab again: e6adc29<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_arose_nglview_commit_e6adc2966ab64c763244266119f37a7e6f19cf40&d=DwMFaQ&c=HPMtquzZjKY31rtkyGRFnQ&r=8waEScVAJus7pLy7oGBweQ&m=X5merpplkg4e7UWlUQRNAQ276g5qnj7jVo3_jS2aVYI&s=tvzXEKmDLAs5a_8tX6NxvR-5yaQW9W7t0BT77M6nnF8&e=>

Please follow below

cd /nglview/root/folder
git clean -fdx .
git pull
source devtools/nglview-jupyterlab.sh

# then go to another folder (to avoid import nglview source code)
jupyter lab

I've tried above several times and seems work for me.

[jupyterlab]<https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_4451957_29302363-2D74837f90-2D8151-2D11e7-2D8285-2D90ebb354ca74.png&d=DwMFaQ&c=HPMtquzZjKY31rtkyGRFnQ&r=8waEScVAJus7pLy7oGBweQ&m=X5merpplkg4e7UWlUQRNAQ276g5qnj7jVo3_jS2aVYI&s=s5z47F9idFPDv7vKPbGNPM_qrshvYgFoFApDOH-BS2k&e=>

[jupyterlab-version]<https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_4451957_29302402-2Dc5c0555e-2D8151-2D11e7-2D8e41-2Dea90f3fa9951.png&d=DwMFaQ&c=HPMtquzZjKY31rtkyGRFnQ&r=8waEScVAJus7pLy7oGBweQ&m=X5merpplkg4e7UWlUQRNAQ276g5qnj7jVo3_jS2aVYI&s=bYP4cjo0w5esmZNyzi4nZeWvj_sW8NM8bsxZCgfoy6o&e=>

**Comment by pfajer** [comment] 2017-08-15 04:49
Hai,

I could not resist, but I got this error:
(I am not as savvy as I might seem,  I would need to consult my computer guy what “committing or stashing change” mean in this context)

P


(Python3) fajer@MacBookPro-15:~/anaconda/nglview$ git pull
remote: Counting objects: 83, done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 83 (delta 63), reused 82 (delta 62), pack-reused 0
Unpacking objects: 100% (83/83), done.
From https://github.com/arose/nglview
   3eaf051..e6adc29  master     -> origin/master
   3e3eea6..7072fc6  gh-pages   -> origin/gh-pages
Updating 3eaf051..e6adc29
error: Your local changes to the following files would be overwritten by merge:
nglview/static/index.js
nglview/static/index.js.map
Please commit your changes or stash them before you merge.
Aborting


On Aug 15, 2017, at 12:36 AM, Hai Nguyen <notifications@github.com<mailto:notifications@github.com>> wrote:


@pfajer<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_pfajer&d=DwMFaQ&c=HPMtquzZjKY31rtkyGRFnQ&r=8waEScVAJus7pLy7oGBweQ&m=X5merpplkg4e7UWlUQRNAQ276g5qnj7jVo3_jS2aVYI&s=x2uWY8Utq4VmNcx2LdZPmz9YuA92QrBuPgkykTJfrKY&e=> I think I make nglview works with jupyterlab again: e6adc29<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_arose_nglview_commit_e6adc2966ab64c763244266119f37a7e6f19cf40&d=DwMFaQ&c=HPMtquzZjKY31rtkyGRFnQ&r=8waEScVAJus7pLy7oGBweQ&m=X5merpplkg4e7UWlUQRNAQ276g5qnj7jVo3_jS2aVYI&s=tvzXEKmDLAs5a_8tX6NxvR-5yaQW9W7t0BT77M6nnF8&e=>

Please follow below

cd /nglview/root/folder
git clean -fdx .
git pull
source devtools/nglview-jupyterlab.sh

# then go to another folder (to avoid import nglview source code)
jupyter lab

I've tried above several times and seems work for me.

[jupyterlab]<https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_4451957_29302363-2D74837f90-2D8151-2D11e7-2D8285-2D90ebb354ca74.png&d=DwMFaQ&c=HPMtquzZjKY31rtkyGRFnQ&r=8waEScVAJus7pLy7oGBweQ&m=X5merpplkg4e7UWlUQRNAQ276g5qnj7jVo3_jS2aVYI&s=s5z47F9idFPDv7vKPbGNPM_qrshvYgFoFApDOH-BS2k&e=>

[jupyterlab-version]<https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_4451957_29302402-2Dc5c0555e-2D8151-2D11e7-2D8e41-2Dea90f3fa9951.png&d=DwMFaQ&c=HPMtquzZjKY31rtkyGRFnQ&r=8waEScVAJus7pLy7oGBweQ&m=X5merpplkg4e7UWlUQRNAQ276g5qnj7jVo3_jS2aVYI&s=bYP4cjo0w5esmZNyzi4nZeWvj_sW8NM8bsxZCgfoy6o&e=>

**Comment by hainm** [comment] 2017-08-15 04:50
I see.
Please

```
git checkout .
``` 

to discard any local change first (caused by `cd js && npm install`).

**Comment by pfajer** [comment] 2017-08-15 04:57
Brilliant !!!!!!!!!!

It works

Thanks so much !   (I was vmd-ing in the desperation when your e-mail reached me)

P


On Aug 15, 2017, at 12:50 AM, Hai Nguyen <notifications@github.com<mailto:notifications@github.com>> wrote:


I see.
Please

git checkout .


to discard any local change first (caused by cd js && npm install).

**Comment by hainm** [comment] 2017-08-15 04:58
> It works

You mean you can see nglview in jupyterlab now?

**Comment by pfajer** [comment] 2017-08-15 04:59
YES !!!
On Aug 15, 2017, at 12:58 AM, Hai Nguyen <notifications@github.com<mailto:notifications@github.com>> wrote:


It works

You mean you can see nglview in jupyterlab now?

**Comment by hainm** [comment] 2017-08-15 05:01
> YES

![tenor](https://user-images.githubusercontent.com/4451957/29302799-3f64cacc-8155-11e7-9aab-c6f500b0e8b2.gif)

g9. I close this issue and do feel free to open others.

**Closed by hainm** 2017-08-15 05:01 UTC

**Comment by pfajer** [comment] 2017-08-15 05:09
This is a faint praise, but there is something (even in computational world) about working with scientists.

I am “over the hill” administrator with illusions of  usefulness but I did make my son who is a former graduate of Andy M down the road from you to look at nglview, he hates tcl but it is (was) the best available.  You guys rock.

P
_______________________________
Piotr Fajer
Professor and Director Institute Molecular Biophysics
Department of Biology
Florida State University
pfajer@fsu.edu<mailto:pfajer@fsu.edu>

On Aug 15, 2017, at 1:01 AM, Hai Nguyen <notifications@github.com<mailto:notifications@github.com>> wrote:


YES

[tenor]<https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_4451957_29302799-2D3f64cacc-2D8155-2D11e7-2D9aab-2Dc6f500b0e8b2.gif&d=DwMCaQ&c=HPMtquzZjKY31rtkyGRFnQ&r=8waEScVAJus7pLy7oGBweQ&m=SV389k3tKJsg28MJ7gGEsYIqSaA65pAFy3qgIlL8upQ&s=DmUrZOgX7BACDA4YIoboGSF7noBRfrxOpfbY7xCLVFU&e=>

g9. I close this issue and do feel free to open others.

**Comment by hainm** [comment] 2017-08-15 05:12
Thanks for your nice comment. We really appreciate it. Cheers.
