### ISSUE TITLE
rendered image disappears after 1 second, visible again as long as user/mouse interaction continues

### ISSUE THREAD

**Issue by paul-shannon** [arose/nglview#709] opened 2017-10-15 20:20 UTC
- Version report

```bash
python -c 'import nglview; print(nglview.__version__)':  1.0.b5+6.g6febf48.dirty
python -c 'import ipywidgets; print(ipywidgets.__version__)' 7.0.0
jupyter --version:  4.2.1
jupyter notebook --version: 5.1.0
```
After a fresh pull, and fresh build, the rendered image appears in the output notebook cell, disappears after 1 second, then reappears with every mouse-interaction with the image.  When the interaction stops.

I use this notebook, unmodified from the github repo:
````
representations_and_selection_language.ipynb
````

````
cd ./js; npm update
cd ./js; webpack --config webpack.config.js
pip install -e .
cd ./js; npm install
jupyter nbextension install --user --py nglview
jupyter-nbextension enable --user --py --sys-prefix nglview
````
Any suggestions

**Comment by hainm** [comment] 2017-10-15 20:44
hi,

which web browser you're using? I normally use chrome for development.

PS: per below
```
cd ./js; npm update
cd ./js; webpack --config webpack.config.js
pip install -e .
cd ./js; npm install
jupyter nbextension install --user --py nglview
jupyter-nbextension enable --user --py --sys-prefix nglview
```

you only need to do that if you modify the js/src source code. The prebuilt Js files are in nglview/static.

**Comment by paul-shannon** [comment] 2017-10-15 20:46
Thanks for the speedy reply, and the tip on the build process

I am using Chrome Version 61.0.3163.100 (Official Build) (64-bit)

 - Paul

**Comment by hainm** [comment] 2017-10-15 20:51
hi,

to ensure we are in the same page, can you 

```
cd /nglview/root/folder
git checkout . # to restore the nglview/static/*js files you overwrote
python setup.py install
```

and close your notebook completely (kill the kernel), try again?

**Comment by arose** [comment] 2017-10-15 21:04
With the canvas in focus (just click on it) press key 'a' to turn anti-aliasing off. There seems to be some driver/webgl issue with the webgl extensions used in NGL :(

**Comment by hainm** [comment] 2017-10-15 21:07
ha, so I pass the ball to you now.

**Comment by paul-shannon** [comment] 2017-10-15 21:09
Sorry, Hai, I don’t appear to have the directory structure you describe:


   git remote -v
   origin	https://github.com/arose/nglview.git (fetch)
   origin	https://github.com/arose/nglview.git (push)

git pull origin
ls -l

-rw-r--r--   1 paul  staff      4606 Sep 16 13:10 CHANGELOG.md
-rw-r--r--   1 paul  staff      4248 Sep 16 13:10 CONTRIBUTING.md
-rw-r--r--   1 paul  staff       853 Sep 16 13:10 Dockerfile
-rw-r--r--   1 paul  staff       631 Sep 16 13:10 Dockerfile-jupyterlab
-rw-r--r--   1 paul  staff      1220 Sep 16 13:10 LICENSE
-rw-r--r--   1 paul  staff       324 Sep 16 13:10 MANIFEST.in
-rw-r--r--   1 paul  staff     14202 Sep 16 13:10 README.md
drwxr-xr-x   3 paul  staff       102 Sep 23 07:19 __pycache__
drwxr-xr-x   4 paul  staff       136 Sep 23 07:19 build
-rw-r--r--   1 paul  staff       227 Sep 16 13:10 circle.yml
-rwxr-xr-x   1 paul  staff       377 Sep 16 13:10 conda-requirements-test.sh
drwxr-xr-x  10 paul  staff       340 Oct 15 12:56 devtools
drwxr-xr-x   3 paul  staff       102 Sep 23 07:19 dist
drwxr-xr-x  27 paul  staff       918 Oct 15 12:56 docs
drwxr-xr-x  16 paul  staff       544 Sep 16 13:11 examples
drwxr-xr-x  10 paul  staff       340 Oct 15 13:00 js
drwxr-xr-x   4 paul  staff       136 Oct 15 12:56 jslab
-rw-r--r--   1 paul  staff       466 Oct 15 13:05 makefile
drwxr-xr-x  32 paul  staff      1088 Oct 15 12:56 nglview
drwxr-xr-x   9 paul  staff       306 Sep 23 07:19 nglview.egg-info
-rw-r--r--   1 paul  staff  12210387 Sep 16 13:11 nglview.gif
-rw-r--r--   1 paul  staff    212532 Sep 16 13:11 nglview.png
-rw-r--r--   1 paul  staff      1088 Sep 16 13:11 nightwatch.json
-rw-r--r--   1 paul  staff       209 Sep 16 13:11 pip-requirements-test.txt
-rwxr-xr-x   1 paul  staff       185 Sep 16 13:11 run_tests.sh
-rw-r--r--   1 paul  staff       364 Sep 16 13:11 setup.cfg
-rw-r--r--   1 paul  staff      7987 Sep 16 13:11 setup.py
-rw-r--r--   1 paul  staff       406 Sep 16 13:11 talks.md
-rw-r--r--   1 paul  staff     68611 Sep 16 13:11 versioneer.py

**Comment by paul-shannon** [comment] 2017-10-15 21:24
Interesting…

I only see this behavior in jupyter notebooks, not in a non-jupyter webapp I also work on.

And (alas) in the notebook, you suggestion of ‘a’ for antialiasing does not solve the disappear-until-the-next-mouse-interaction problem.

Anything else I can supply information on?

 - Paul

**Comment by hainm** [comment] 2017-10-15 22:11
hi
1. 
```
ls nglview/static/
```
it's python thing with nglview/nglview subfoler :D 


2. 
I can not reproduce your issue.

If not too much to ask, can your try each nglview git tag 
```
v1.0.b1
v1.0.b2
v1.0.b3
v1.0.b4
v1.0.b5
```

e.g:
```
git checkout v1.0.b4
pip uninstall nglview
python setup.py install
```

and try again? make sure to close the notebook and its kernel to clear the cache. thanks

**Comment by paul-shannon** [comment] 2017-10-15 22:18
Maybe this is helpful?  I see the same behavior at

     https://www.rcsb.org/pdb/ngl/ngl.do?pdbid=5H73

The structure briefly appears.
It disappears.
Click-dragging on the canvas brings the structure back into view.


 - Paul

**Comment by paul-shannon** [comment] 2017-10-16 17:35
Is this (https://www.rcsb.org/pdb/ngl/ngl.do?pdbid=5H73) a sufficient bug report, or can I still help by doing the successive versions test @hainm proposed yesterday afternoon?  I'll be glad to do that but do not wish to duplicate effort.  Let me know, please!

**Comment by arose** [comment] 2017-10-16 17:58
Hi @paul-shannon does the structure disappears for you here (http://nglviewer.org/ts2/?load=rcsb://5H73&debug=1) as well?

**Comment by hainm** [comment] 2017-10-16 18:29
@paul-shannon  no you don't need to do anything with nglview for now.

**Comment by paul-shannon** [comment] 2017-10-16 18:37
Yes, same disappearance happens here.  Click-drag brings the model back as long as the mouse is down.

 - Paul

**Comment by arose** [comment] 2017-10-16 18:57
ok, can you please try pressing 'a' on that page

**Comment by paul-shannon** [comment] 2017-10-16 18:59
‘a’ fixes it.  (Thanks for this reminder)

**Comment by harryjubb** [comment] 2017-10-31 12:58
Hi @arose, this is reproducible on 2015 13" Macbook Pros with Intel Iris Graphics 6100 1536 MB. Interestingly having no problems on mid-2015 15" MBP with AMD Radeon R9 M370X 2048 MB and on a 2017 Macbook.

Where it doesn't work it only seems to happen in Chrome (v61 and v62), Firefox and Safari are fine. Pressing 'a' doesn't fix it for http://nglviewer.org/ngl/?load=rcsb://5H73&debug=1 but it does for http://nglviewer.org/ts2/?load=rcsb://5H73&debug=1.

Has this been transferred into an issue in arose/ngl? Any idea what the cause is and why it seems to only affect certain machines?

**Comment by arose** [comment] 2017-11-04 04:36
just released a version (1.0.0-beta.5 as well as latest ts2 branch) that has a workaround for it

**Comment by hainm** [comment] 2017-11-04 19:18
@paul-shannon I just update to nglview too. Please try the master branch

https://github.com/arose/nglview/commit/e504af1c02bb6dd37f9c45d030cc14d2e4cd05b7

**Comment by paul-shannon** [comment] 2017-11-06 18:28
1.0.0-beta.5 works great for me.  Thank you!

**Comment by hainm** [comment] 2017-11-06 18:47
thanks for testing. I close this issue. Do feel free to reopen or open others.

**Closed by hainm** 2017-11-06 18:47 UTC
